### ISSUE TITLE
Panic: runtime error

### ISSUE THREAD

**Issue by deining** [muquit/mailsend-go#61]
```
mailsend-go -V
@(#) mailsend-go v1.0.10
```

**How to reproduce:**

```
mailsend-go -smtp foo -ssl -info
```
This results in

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x24 pc=0x5b0367]

goroutine 1 [running]:
crypto/tls.(*Conn).Handshake(0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.15.5/libexec/src/crypto/tls/conn.go:1349 +0x47
crypto/tls.(*Conn).Read(0x0, 0xc0000f0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.15.5/libexec/src/crypto/tls/conn.go:1239 +0x53
bufio.(*Reader).fill(0xc000048fc0)
        /usr/local/Cellar/go/1.15.5/libexec/src/bufio/bufio.go:101 +0x105
bufio.(*Reader).ReadSlice(0xc000048fc0, 0x20300a, 0x1ad800, 0x5ae800, 0x203000, 0x203000, 0x203000)
        /usr/local/Cellar/go/1.15.5/libexec/src/bufio/bufio.go:360 +0x3d
bufio.(*Reader).ReadLine(0xc000048fc0, 0x90, 0x88, 0x68aa60, 0x6425d8, 0x66eb40, 0x7f32c5bdd070)
        /usr/local/Cellar/go/1.15.5/libexec/src/bufio/bufio.go:389 +0x34
net/textproto.(*Reader).readLineSlice(0xc0000de090, 0xc00003f858, 0x40de18, 0x90, 0x68aa60, 0x1)
        /usr/local/Cellar/go/1.15.5/libexec/src/net/textproto/reader.go:58 +0x6c
net/textproto.(*Reader).ReadLine(...)
        /usr/local/Cellar/go/1.15.5/libexec/src/net/textproto/reader.go:39
net/textproto.(*Reader).readCodeLine(0xc0000de090, 0xdc, 0x7f329ef48888, 0xc000048fc0, 0xc000076380, 0xc000048fc0, 0xc0000f1000, 0x0)
        /usr/local/Cellar/go/1.15.5/libexec/src/net/textproto/reader.go:193 +0x2f
net/textproto.(*Reader).ReadResponse(0xc0000de090, 0xdc, 0xc0000de090, 0x7f329ef48858, 0x0, 0x0, 0x6fbf00)
        /usr/local/Cellar/go/1.15.5/libexec/src/net/textproto/reader.go:271 +0x4d
main.printSMTPInfo(0x7ffd77728832, 0xe, 0x24b, 0x1)
        /Users/muquit/dev/go/src/github.com/muquit/mailsend-go/smtp_info.go:71 +0x226
main.xprintSMTPInfo()
        /Users/muquit/dev/go/src/github.com/muquit/mailsend-go/main.go:853 +0x105
main.main()
        /Users/muquit/dev/go/src/github.com/muquit/mailsend-go/main.go:1053 +0x2a19
```

**Comment by muquit** [comment]
I believe your last pull request fixed the bug in master branch. I just did not get any chance to make a build yet.

**Comment by deining** [comment]
> I believe your last pull request fixed the bug in master branch.

Indeed, the error doesn't occur with HEAD of  `master` branch.

> I just did not get any chance to make a build yet.

Looking forward seeing a new build soon. Thanks for your efforts.
